[package]
name = "rusttest"
version = "0.1.0"
authors = ["zhuxiaozhou <zhuxiaozhou@huohua.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
serde = "1"
serde_json = "1"